export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";

export const ADDPRODUCT = "ADDPRODUCT";
export const GETPRODUCTS = "GETPRODUCTS";

export const GETUSERS = "GETUSERS";

export const GETORDERITEMS = "GETORDERITEMS";
export const ADDORDERITEM = "ADDORDERITEM";
export const REMOVEORDERITEM = "REMOVEORDERITEM";

export const GETORDERS = "GETORDERS";
export const ADDORDER = "ADDORDER";
export const UPDATEORDER = "UPDATEORDER";

export const ADDPAYMENTCARD = "ADDPAYMENTCARD";
export const GETPAYMENTCARDS = "GETPAYMENTCARDS";
